// zh-CN UI dictionary (Milestone 6-I). Keys are the English source strings —
// t(s) returns ZH[s] when the language is zh-CN, otherwise the key itself, so
// a missing entry degrades gracefully to English. Backend strings (log lines,
// error messages) intentionally stay English: they are diagnostics.
export const ZH = {
  // ── capture overlay ──
  'Drag to select · Enter to save · Esc to cancel': '拖拽选择 · Enter 保存 · Esc 取消',
  '✓ Save': '✓ 保存',
  // ── sidebar ──
  Settings: '设置',
  'General Settings': '通用设置',
  'Hosts & Targets': '主机与目标',
  'System Logs': '系统日志',
  // ── general tab ──
  'Configure global screenshot format, hotkeys, and injection preferences.':
    '配置全局截图格式、快捷键与注入偏好。',
  'Image Config': '图片配置',
  'Output Format': '输出格式',
  'Markdown (![image](path))': 'Markdown（![image](path)）',
  'Raw Path': '裸路径（Raw Path）',
  'Inline Base64 Data URI': '内联 Base64 Data URI',
  'Compression Quality': '压缩质量',
  'Max Dimension (Pixels)': '最大边长（像素）',
  'No Limit': '不限',
  'System Integration': '系统集成',
  'Upload Hotkey': '上传热键',
  '(Recording...)': '（录制中…）',
  '(click & press keys)': '（点击后按键）',
  'Screenshot Hotkey': '截图热键',
  '(region capture)': '（区域截图）',
  Reset: '重置',
  'Injection Mode': '注入模式',
  'Auto — per-app strategy (recommended)': 'Auto — 按应用自动选择（推荐）',
  'Direct — type the path (no clipboard)': 'Direct — 直接键入路径（不占剪贴板）',
  'Copy Only — manual Ctrl+V': 'Copy — 仅复制到剪贴板，手动 Ctrl+V',
  'Wrap in Single Quotes': '单引号包裹',
  "Wrap generated link in 'quotes'": "生成的链接用单引号包裹",
  'Launch on Boot': '开机启动',
  'Start img2cli automatically': '自动启动 img2cli',
  'Enable Desktop Notifications': '桌面通知',
  'Show tips on screenshot success': '截图成功时显示提示',
  'Interface Theme': '界面主题',
  'Display Language': '显示语言',
  'Advanced Paths': '高级路径',
  'Local Temporary Directory': '本地临时目录',
  'Default (Temp Dir/img2cli)': '默认（临时目录/img2cli）',
  'Clean Expired Image Files (Days)': '清理过期图片（天）',
  'Save Settings': '保存设置',
  // ── hosts tab ──
  'Configure remote SSH servers and local workspace directory routing.':
    '配置远程 SSH 服务器与本地目录的路由规则。',
  'Host Name': '主机名',
  'e.g. My GPU Server': '例如 我的GPU服务器',
  'Host IP / Address': '主机 IP / 地址',
  Port: '端口',
  Username: '用户名',
  'Remote Copy Destination Folder': '远程存放目录',
  Password: '密码',
  '(OS keyring)': '（系统密钥库）',
  '●●●●●● (saved) — type a new one to update': '●●●●●●（已保存）— 输入新密码可更新',
  'blank: uses your SSH key (~/.ssh)': '留空：使用 SSH 密钥（~/.ssh）',
  'Remember Password (OS Keyring)': '记住密码（系统密钥库）',
  '✓ Password saved (keyring)': '✓ 密码已保存（密钥库）',
  clear: '清除',
  'No password → will use your SSH key (~/.ssh)': '无密码 → 将使用 SSH 密钥（~/.ssh）',
  'Testing...': '测试中…',
  'Test Connection': '测试连接',
  'Dynamic Router Targets': '动态路由目标',
  'Load SSH Config': '导入 SSH 配置',
  'Add Target': '添加目标',
  Status: '状态',
  'Host Name / Alias': '主机名 / 别名',
  Type: '类型',
  Details: '详情',
  Actions: '操作',
  'Set Default': '设为默认',
  Edit: '编辑',
  Delete: '删除',
  'No routing targets configured. Clipboard uploads will fallback to default host.':
    '尚未配置路由目标。剪贴板上传将回退到默认主机。',
  // ── logs tab ──
  'Real-time daemon events and screenshot processing logs.': '实时守护进程事件与截图处理日志。',
  'Copy All': '复制全部',
  'Export…': '导出…',
  'Clear Logs': '清空日志',
  'No logs loaded. Press global hotkey to trigger daemon activity.':
    '暂无日志。按全局热键触发守护进程活动。',
  // ── add/edit target modal ──
  'Edit Router Target': '编辑路由目标',
  'Add Router Target': '添加路由目标',
  'Target Type': '目标类型',
  'SSH (Remote Server)': 'SSH（远程服务器）',
  'Local Folder': '本地目录',
  'e.g. GPU-90, WSL': '例如 GPU-90、WSL',
  'Local Copy Destination Folder': '本地存放目录',
  'e.g. C:\\users\\docs\\images': '例如 C:\\users\\docs\\images',
  Cancel: '取消',
  Save: '保存',
  // ── ssh loader modal ──
  'Load OpenSSH config': '导入 OpenSSH 配置',
  'Browse…': '浏览…',
  Load: '加载',
  'Search hosts (alias / host / user)...': '搜索主机（别名 / 地址 / 用户名）…',
  'No hosts found.': '未找到主机。',
  'Select All': '全选',
  'Import Selected': '导入选中',
  // ── toast / JS messages ──
  'Settings saved successfully!': '设置已保存！',
  'Failed to save settings:': '保存设置失败：',
  'Failed to load configuration:': '加载配置失败：',
  'Logs copied to clipboard.': '日志已复制到剪贴板。',
  'Failed to copy logs:': '复制日志失败：',
  'Failed to export logs:': '导出日志失败：',
  'Password cleared.': '密码已清除。',
  'Failed to clear:': '清除失败：',
  'Connection failed:': '连接失败：',
  'Target deleted.': '目标已删除。',
  'Match pattern cannot be empty.': '匹配规则不能为空。',
  'Target saved · password stored in keyring': '目标已保存 · 密码已存入密钥库',
  'Target saved · password cleared from keyring': '目标已保存 · 密码已从密钥库清除',
  'Target updated.': '目标已更新。',
  'Logs exported to:': '日志已导出到：',
  'Failed to load SSH config:': '加载 SSH 配置失败：',
  'Failed to open file dialog:': '打开文件对话框失败：',
  Imported: '已导入',
  'host(s) as router targets': '个主机为路由目标',
  'host(s),': '个主机，',
  'duplicate(s) skipped': '个重复项已跳过',
  'set as the default SSH host.': '已设为默认 SSH 主机。',
  'Saved target, but password not stored:': '目标已保存，但密码未存储：',
  // ── capture options + overlay (6-J/6-L) ──
  'Drag to select · Click a window to snap · Enter to save · Esc to cancel':
    '拖拽选择 · 点击选中窗口 · Enter 保存 · Esc 取消',
  'Capture Options': '截屏选项',
  'Auto-detect windows': '自动识别窗口',
  'Click to snap the window under the cursor': '点击即可选中光标所在窗口',
  'Remember last selection': '记住上次选区',
  'Preload the previous region on the next capture': '下次截图预载上次选区，适合重复截同一区域',
  'Show capture hints': '显示截图提示',
  'Selection border width (px)': '选区边框宽度（像素）',
  'Mask opacity (%)': '遮罩浓度（%）',
  // ── hosts cards (6-H) ──
  Test: '测试',
  Local: '本地',
  Default: '默认',
  Connected: '已连通',
};

// Chinese display names for the theme selector.
export const THEME_ZH = {
  'apple-dark': 'Apple 深色',
  'apple-light': 'Apple 浅色',
  dracula: 'Dracula',
  nord: 'Nord',
  gruvbox: 'Gruvbox',
  cyberpunk: 'Cyberpunk',
};
